server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location = /manifest.webmanifest {
        default_type application/manifest+json;
        add_header Cache-Control "no-cache";
    }

    location = /push-sw.js {
        default_type application/javascript;
        add_header Cache-Control "no-cache";
    }

    # Gzip Compression
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml image/png image/jpeg;
    gzip_min_length 1000;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
