import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    padding: 20,
    overflow: 'hidden',
  },
  contentOverlay: {
    flex: 1,
    zIndex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 24,
  },
  card: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: 'rgba(15, 35, 68, 0.46)',
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    shadowColor: '#030B16',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 6,
  },
  hero: {
    marginBottom: 12,
  },
  heroImageWrap: {
    width: 88,
    height: 88,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.86)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
  },
  heroImage: {
    width: 88,
    height: 88,
    resizeMode: 'cover',
  },
  title: {
    fontSize: 25,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 15,
    color: '#D9E4FF',
    marginBottom: 28,
    textAlign: 'center',
  },
  inputGroup: {
    width: '100%',
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(233, 239, 248, 0.88)',
    marginBottom: 9,
    letterSpacing: 0.2,
  },
  divider: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#7CC0FF',
    marginBottom: 26,
  },
  fieldWrapper: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    borderWidth: 1.25,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    overflow: 'hidden',
  },
  fieldWrapperFocus: {
    borderColor: '#60B8FF',
    shadowColor: '#005FF7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  input: {
    width: '100%',
    flex: 1,
    minHeight: 50,
    paddingVertical: 0,
    paddingHorizontal: 12,
    fontSize: 15,
    color: '#F1F5F9',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    includeFontPadding: false,
  },
  passwordWrapper: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    borderWidth: 1.25,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    overflow: 'hidden',
  },
  passwordInput: {
    flex: 1,
    minHeight: 50,
    paddingVertical: 0,
    paddingHorizontal: 12,
    fontSize: 15,
    color: '#F1F5F9',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    includeFontPadding: false,
  },
  eyeButton: {
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255,255,255,0.16)',
  },
  fieldIcon: {
    marginLeft: 12,
    marginRight: 8,
  },
  forgotRow: {
    width: '100%',
    alignItems: 'flex-end',
    marginTop: 2,
    marginBottom: 18,
  },
  forgotText: {
    color: '#A9D5FF',
    fontSize: 12.5,
    fontWeight: '600',
  },
  forgotLink: {
    cursor: 'pointer',
  },
  forgotLinkPressed: {
    opacity: 0.82,
  },
  button: {
    width: '100%',
    backgroundColor: '#7EC3FF',
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonPressed: {
    opacity: 0.88,
  },
  buttonText: {
    color: '#082246',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  footer: {
    marginTop: 16,
    alignItems: 'center',
    width: '100%',
  },
  footerText: {
    color: '#D2DFF8',
    fontSize: 12.5,
  },
  footerAction: {
    color: '#A9D5FF',
    fontSize: 13,
    marginTop: 3,
    fontWeight: '600',
  },
  backLinkPressed: {
    opacity: 0.82,
  },
  backLink: {
    cursor: 'pointer',
  },
});
