import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    padding: 18,
    overflow: 'hidden',
    backgroundColor: '#04152A',
  },
  webBackground: {
    backgroundImage:
      'linear-gradient(145deg, #04152A 0%, #061B35 52%, #08264A 100%)',
  } as any,
  ambientGlow: {
    position: 'absolute',
    top: '12%',
    left: '5%',
    width: '90%',
    height: '72%',
    borderRadius: 999,
    backgroundColor: 'rgba(40, 130, 255, 0.055)',
  },
  webAmbientGlow: {
    backgroundImage:
      'radial-gradient(circle at 50% 40%, rgba(40, 130, 255, 0.12), transparent 55%)',
    backgroundColor: 'transparent',
  } as any,
  },
  contentOverlay: {
    flex: 1,
    zIndex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  card: {
    width: '89%',
    maxWidth: 380,
    backgroundColor: 'rgba(7, 25, 50, 0.38)',
    borderRadius: 22,
    paddingHorizontal: 24,
    paddingVertical: 26,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(170, 205, 240, 0.30)',
    shadowColor: '#030B16',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 6,
    backdropFilter: 'blur(12px)',
  },
  hero: {
    marginBottom: 10,
  },
  heroImageWrap: {
    width: 94,
    height: 94,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroImage: {
    width: 94,
    height: 94,
    resizeMode: 'contain',
  },
  title: {
    fontSize: 27,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 15.5,
    color: 'rgba(255, 255, 255, 0.75)',
    marginBottom: 22,
    textAlign: 'center',
  },
  inputGroup: {
    width: '100%',
    marginBottom: 15,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.85)',
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  divider: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#6ABEFF',
    marginBottom: 23,
  },
  fieldWrapper: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    height: 55,
    borderWidth: 1,
    borderColor: 'rgba(180, 210, 240, 0.24)',
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    overflow: 'hidden',
  },
  fieldWrapperFocus: {
    borderColor: '#60B8FF',
    shadowColor: '#005FF7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  input: {
    width: '100%',
    flex: 1,
    minHeight: 55,
    paddingVertical: 0,
    paddingHorizontal: 12,
    fontSize: 15,
    color: '#F1F5F9',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    includeFontPadding: false,
  },
  passwordWrapper: {
    width: '100%',
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    height: 55,
    borderWidth: 1,
    borderColor: 'rgba(180, 210, 240, 0.24)',
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    overflow: 'hidden',
  },
  passwordInput: {
    flex: 1,
    width: '100%',
    minHeight: 55,
    paddingVertical: 0,
    paddingLeft: 12,
    paddingRight: 52,
    fontSize: 15,
    color: '#F1F5F9',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    includeFontPadding: false,
  },
  eyeButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 2,
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
    height: 55,
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255,255,255,0.16)',
  },
  fieldIcon: {
    marginLeft: 12,
    marginRight: 8,
  },
  button: {
    width: '100%',
    minHeight: 55,
    backgroundColor: '#72BDF5',
    justifyContent: 'center',
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonPressed: {
    opacity: 0.88,
  },
  buttonText: {
    color: '#082246',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  installButton: {
    width: '100%',
    minHeight: 53,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#62B7F4',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'transparent',
  },
  installButtonText: {
    color: '#D9ECFF',
    fontSize: 14,
    fontWeight: '700',
  },
  updateBanner: {
    width: '100%',
    marginTop: 14,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(126, 195, 255, 0.32)',
    backgroundColor: 'rgba(5, 28, 51, 0.72)',
    gap: 10,
  },
  updateCopy: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  updateText: {
    color: '#EAF5FF',
    fontSize: 13,
    fontWeight: '600',
  },
  updateButton: {
    minHeight: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(114, 189, 245, 0.16)',
  },
  updateButtonText: {
    color: '#8DCCFA',
    fontSize: 13,
    fontWeight: '700',
  },
  desktopWrapper: {
    padding: 36,
  },
  desktopScrollContent: {
    paddingVertical: 36,
  },
  desktopCard: {
    maxWidth: 380,
    paddingHorizontal: 32,
    paddingVertical: 30,
    borderRadius: 24,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.38,
    shadowRadius: 30,
  },
  desktopTitle: {
    fontSize: 29,
  },
});
